-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_otp]: function definitions
import Aeneas
import AeneasOtp.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AeneasOtp

/-- [aeneas_otp::encrypt]:
    Source: 'src/lib.rs', lines 4:0-6:1
    Visibility: public -/
def encrypt (key : Std.U8) (message : Std.U8) : Result Std.U8 := do
  ok (key ^^^ message)

/-- [aeneas_otp::decrypt]:
    Source: 'src/lib.rs', lines 9:0-11:1
    Visibility: public -/
def decrypt (key : Std.U8) (ciphertext : Std.U8) : Result Std.U8 := do
  ok (key ^^^ ciphertext)

end AeneasOtp
