-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_merkle]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import FastcryptoMerkle.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open FastcryptoMerkle

/-- [core::convert::{impl core::convert::AsRef<U> for &'_0 T}::as_ref]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 720:4-720:26
    Name pattern: [core::convert::{core::convert::AsRef<&'0 @T, @U>}::as_ref]
    Visibility: public -/
@[rust_fun "core::convert::{core::convert::AsRef<&'0 @T, @U>}::as_ref"]
axiom Shared0T.Insts.CoreConvertAsRef.as_ref
  {T : Type} {U : Type} (AsRefInst : core.convert.AsRef T U) : T → Result U

/-- [core::convert::{impl core::convert::AsRef<[T]> for [T]}::as_ref]:
    Source: '/rustc/library/core/src/convert/mod.rs', lines 850:4-850:28
    Name pattern: [core::convert::{core::convert::AsRef<[@T], [@T]>}::as_ref]
    Visibility: public -/
@[rust_fun "core::convert::{core::convert::AsRef<[@T], [@T]>}::as_ref"]
axiom Slice.Insts.CoreConvertAsRefSlice.as_ref
  {T : Type} : Slice T → Result (Slice T)

/-- [core::hint::must_use]:
    Source: '/rustc/library/core/src/hint.rs', lines 613:0-613:39
    Name pattern: [core::hint::must_use]
    Visibility: public -/
@[rust_fun "core::hint::must_use"]
axiom core.hint.must_use {T : Type} : T → Result T

/-- [alloc::fmt::format]:
    Source: '/rustc/library/alloc/src/fmt.rs', lines 649:0-649:52
    Name pattern: [alloc::fmt::format]
    Visibility: public -/
@[rust_fun "alloc::fmt::format"]
axiom alloc.fmt.format : core.fmt.Arguments → Result String

/-- [alloc::vec::{alloc::vec::Vec<T>}::reserve]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1460:4-1460:48
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::reserve]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::reserve"]
axiom alloc.vec.Vec.reserve
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (alloc.vec.Vec T)

/-- [alloc::vec::{impl core::convert::AsRef<[T]> for alloc::vec::Vec<T>}::as_ref]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4401:4-4401:28
    Name pattern: [alloc::vec::{core::convert::AsRef<alloc::vec::Vec<@T>, [@T]>}::as_ref]
    Visibility: public -/
@[rust_fun
  "alloc::vec::{core::convert::AsRef<alloc::vec::Vec<@T>, [@T]>}::as_ref"]
axiom alloc.vec.Vec.Insts.CoreConvertAsRefSlice.as_ref
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T)

/-- [fastcrypto::hash::HashFunction::OUTPUT_SIZE]
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/hash.rs', lines 82:4-82:28
    Name pattern: [fastcrypto::hash::HashFunction::OUTPUT_SIZE]
    Visibility: public -/
@[trait_default, rust_const "fastcrypto::hash::HashFunction::OUTPUT_SIZE"]
axiom fastcrypto.hash.HashFunction.OUTPUT_SIZE.default {Self : Type}
  {DIGEST_LENGTH : Std.Usize} (HashFunctionInst : fastcrypto.hash.HashFunction
  Self DIGEST_LENGTH) : Result Std.Usize

