-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_merkle]: function definitions
import Aeneas
import FastcryptoMerkle.Code.Types
import FastcryptoMerkle.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace FastcryptoMerkle

/-- Trait implementation: [core::array::equality::{impl core::cmp::PartialEq<[U; N]> for [T; N]}]
    Source: '/rustc/library/core/src/array/equality.rs', lines 5:0-7:28
    Name pattern: [core::cmp::PartialEq<[@T; @N], [@U; @N]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T; @N], [@U; @N]>"]
def Array.Insts.CoreCmpPartialEqArray {T : Type} {U : Type} (N : Std.Usize)
  (cmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (Array T N)
  (Array U N) := {
  eq := core.array.equality.PartialEqArray.eq cmpPartialEqInst
}

/-- Trait implementation: [core::convert::{impl core::convert::AsRef<U> for &'_0 T}]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 715:0-717:24
    Name pattern: [core::convert::AsRef<&'0 @T, @U>] -/
@[reducible, rust_trait_impl "core::convert::AsRef<&'0 @T, @U>"]
def Shared0T.Insts.CoreConvertAsRef {T : Type} {U : Type} (AsRefInst :
  core.convert.AsRef T U) : core.convert.AsRef T U := {
  as_ref := Shared0T.Insts.CoreConvertAsRef.as_ref AsRefInst
}

/-- Trait implementation: [core::convert::{impl core::convert::AsRef<[T]> for [T]}]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 848:0-848:32
    Name pattern: [core::convert::AsRef<[@T], [@T]>] -/
@[reducible, rust_trait_impl "core::convert::AsRef<[@T], [@T]>"]
def Slice.Insts.CoreConvertAsRefSlice (T : Type) : core.convert.AsRef (Slice T)
  (Slice T) := {
  as_ref := Slice.Insts.CoreConvertAsRefSlice.as_ref
}

/-- Trait implementation: [core::fmt::num::imp::{impl core::fmt::Display for usize}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 134:8-134:39
    Name pattern: [core::fmt::Display<usize>] -/
@[reducible, rust_trait_impl "core::fmt::Display<usize>"]
def Usize.Insts.CoreFmtDisplay : core.fmt.Display Std.Usize := {
  fmt := core.fmt.num.imp.DisplayUsize.fmt
}

/-- Trait implementation: [alloc::vec::{impl core::convert::AsRef<[T]> for alloc::vec::Vec<T>}]
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4400:0-4400:46
    Name pattern: [core::convert::AsRef<alloc::vec::Vec<@T>, [@T]>] -/
@[reducible, rust_trait_impl "core::convert::AsRef<alloc::vec::Vec<@T>, [@T]>"]
def alloc.vec.Vec.Insts.CoreConvertAsRefSlice (T : Type) (A : Type) :
  core.convert.AsRef (alloc.vec.Vec T) (Slice T) := {
  as_ref := alloc.vec.Vec.Insts.CoreConvertAsRefSlice.as_ref A
}

/-- [fastcrypto::merkle::LEAF_PREFIX]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 18:0-18:30
    Name pattern: [fastcrypto::merkle::LEAF_PREFIX]
    Visibility: public -/
@[global_simps, irreducible, rust_const "fastcrypto::merkle::LEAF_PREFIX"]
def fastcrypto.merkle.LEAF_PREFIX : Array Std.U8 1#usize :=
  Array.make 1#usize [ 0#u8 ]

/-- [fastcrypto::merkle::INNER_PREFIX]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 19:0-19:31
    Name pattern: [fastcrypto::merkle::INNER_PREFIX]
    Visibility: public -/
@[global_simps, irreducible, rust_const "fastcrypto::merkle::INNER_PREFIX"]
def fastcrypto.merkle.INNER_PREFIX : Array Std.U8 1#usize :=
  Array.make 1#usize [ 1#u8 ]

/-- [fastcrypto::merkle::EMPTY_NODE]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 20:0-20:38
    Name pattern: [fastcrypto::merkle::EMPTY_NODE]
    Visibility: public -/
@[global_simps, irreducible, rust_const "fastcrypto::merkle::EMPTY_NODE"]
def fastcrypto.merkle.EMPTY_NODE : Array Std.U8 32#usize :=
  Array.repeat 32#usize 0#u8

/-- [fastcrypto::merkle::{impl core::clone::Clone for fastcrypto::merkle::Node}::clone]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 23:9-23:14
    Name pattern: [fastcrypto::merkle::{core::clone::Clone<fastcrypto::merkle::Node>}::clone]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{core::clone::Clone<fastcrypto::merkle::Node>}::clone"]
def fastcrypto.merkle.Node.Insts.CoreCloneClone.clone
  (self : fastcrypto.merkle.Node) : Result fastcrypto.merkle.Node := do
  match self with
  | fastcrypto.merkle.Node.Empty => ok fastcrypto.merkle.Node.Empty
  | fastcrypto.merkle.Node.Digest __self_0 =>
    let a ← core.array.CloneArray.clone core.clone.CloneU8 __self_0
    ok (fastcrypto.merkle.Node.Digest a)

/-- [fastcrypto::merkle::{impl core::cmp::PartialEq<fastcrypto::merkle::Node> for fastcrypto::merkle::Node}::eq]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 23:16-23:25
    Name pattern: [fastcrypto::merkle::{core::cmp::PartialEq<fastcrypto::merkle::Node, fastcrypto::merkle::Node>}::eq]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{core::cmp::PartialEq<fastcrypto::merkle::Node, fastcrypto::merkle::Node>}::eq"]
def fastcrypto.merkle.Node.Insts.CoreCmpPartialEqNode.eq
  (self : fastcrypto.merkle.Node) (other : fastcrypto.merkle.Node) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | fastcrypto.merkle.Node.Empty => ok true
    | fastcrypto.merkle.Node.Digest __self_0 =>
      match other with
      | fastcrypto.merkle.Node.Empty => ok true
      | fastcrypto.merkle.Node.Digest __arg1_0 =>
        core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 __self_0
          __arg1_0
  else ok false

/-- [fastcrypto::merkle::{fastcrypto::merkle::Node}::bytes]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 33:4-33:43
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::Node}::bytes]
    Visibility: public -/
@[rust_fun "fastcrypto::merkle::{fastcrypto::merkle::Node}::bytes"]
def fastcrypto.merkle.Node.bytes
  (self : fastcrypto.merkle.Node) : Result (Array Std.U8 32#usize) := do
  match self with
  | fastcrypto.merkle.Node.Empty => ok fastcrypto.merkle.EMPTY_NODE
  | fastcrypto.merkle.Node.Digest val => ok val

/-- [fastcrypto::merkle::{impl core::convert::From<fastcrypto::hash::Digest<32usize>> for fastcrypto::merkle::Node}::from]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 42:4-42:46
    Name pattern: [fastcrypto::merkle::{core::convert::From<fastcrypto::merkle::Node, fastcrypto::hash::Digest<32>>}::from]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{core::convert::From<fastcrypto::merkle::Node, fastcrypto::hash::Digest<32>>}::from"]
def fastcrypto.merkle.Node.Insts.CoreConvertFromDigest32.from
  (value : fastcrypto.hash.Digest 32#usize) :
  Result fastcrypto.merkle.Node
  := do
  ok (fastcrypto.merkle.Node.Digest value.digest)

/-- Trait implementation: [fastcrypto::merkle::{impl core::convert::From<fastcrypto::hash::Digest<32usize>> for fastcrypto::merkle::Node}]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 41:0-41:38
    Name pattern: [core::convert::From<fastcrypto::merkle::Node, fastcrypto::hash::Digest<32>>] -/
@[reducible, rust_trait_impl
  "core::convert::From<fastcrypto::merkle::Node, fastcrypto::hash::Digest<32>>"]
def fastcrypto.merkle.Node.Insts.CoreConvertFromDigest32 : core.convert.From
  fastcrypto.merkle.Node (fastcrypto.hash.Digest 32#usize) := {
  «from» := fastcrypto.merkle.Node.Insts.CoreConvertFromDigest32.from
}

/-- [fastcrypto::merkle::inner_hash]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 512:0-514:32
    Name pattern: [fastcrypto::merkle::inner_hash] -/
@[rust_fun "fastcrypto::merkle::inner_hash"]
def fastcrypto.merkle.inner_hash
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (left : fastcrypto.merkle.Node) (right : fastcrypto.merkle.Node) :
  Result fastcrypto.merkle.Node
  := do
  let hash_fun ← hashHashFunctionT32Inst.coredefaultDefaultInst.default
  let hash_fun1 ←
    hashHashFunctionT32Inst.update (Array.Insts.CoreConvertAsRefSlice Std.U8
      1#usize) hash_fun fastcrypto.merkle.INNER_PREFIX
  let a ← fastcrypto.merkle.Node.bytes left
  let hash_fun2 ←
    hashHashFunctionT32Inst.update (Array.Insts.CoreConvertAsRefSlice Std.U8
      32#usize) hash_fun1 a
  let a1 ← fastcrypto.merkle.Node.bytes right
  let hash_fun3 ←
    hashHashFunctionT32Inst.update (Array.Insts.CoreConvertAsRefSlice Std.U8
      32#usize) hash_fun2 a1
  let d ← hashHashFunctionT32Inst.finalize hash_fun3
  core.convert.IntoFrom.into
    fastcrypto.merkle.Node.Insts.CoreConvertFromDigest32 d

/-- [fastcrypto::merkle::leaf_hash]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 502:0-504:32
    Name pattern: [fastcrypto::merkle::leaf_hash] -/
@[rust_fun "fastcrypto::merkle::leaf_hash"]
def fastcrypto.merkle.leaf_hash
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (input : Slice Std.U8) :
  Result fastcrypto.merkle.Node
  := do
  let hash_fun ← hashHashFunctionT32Inst.coredefaultDefaultInst.default
  let hash_fun1 ←
    hashHashFunctionT32Inst.update (Array.Insts.CoreConvertAsRefSlice Std.U8
      1#usize) hash_fun fastcrypto.merkle.LEAF_PREFIX
  let hash_fun2 ←
    hashHashFunctionT32Inst.update (Shared0T.Insts.CoreConvertAsRef
      (Slice.Insts.CoreConvertAsRefSlice Std.U8)) hash_fun1 input
  let d ← hashHashFunctionT32Inst.finalize hash_fun2
  core.convert.IntoFrom.into
    fastcrypto.merkle.Node.Insts.CoreConvertFromDigest32 d

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<T>}::compute_root]: loop 0:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 144:8-155:9
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::compute_root]
    Visibility: public -/
@[rust_loop, rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::compute_root"]
def fastcrypto.merkle.MerkleProof.compute_root_loop
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (iter : core.slice.iter.Iter fastcrypto.merkle.Node)
  (current_hash : fastcrypto.merkle.Node) (level_index : Std.Usize) :
  Result fastcrypto.merkle.Node
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok current_hash
  | some sibling =>
    let b ← core.num.Usize.is_multiple_of level_index 2#usize
    let current_hash1 ←
      if b
      then
        fastcrypto.merkle.inner_hash hashHashFunctionT32Inst current_hash
          sibling
      else
        fastcrypto.merkle.inner_hash hashHashFunctionT32Inst sibling
          current_hash
    let level_index1 ← level_index / 2#usize
    fastcrypto.merkle.MerkleProof.compute_root_loop hashHashFunctionT32Inst
      iter1 current_hash1 level_index1
partial_fixpoint

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<T>}::compute_root]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 137:4-137:78
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::compute_root]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::compute_root"]
def fastcrypto.merkle.MerkleProof.compute_root
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (self : fastcrypto.merkle.MerkleProof T) (leaf : Slice Std.U8)
  (leaf_index : Std.Usize) :
  Result (Option fastcrypto.merkle.Node)
  := do
  let path_len := alloc.vec.Vec.len self.path
  let i ← lift (UScalar.cast .Usize core.num.Usize.BITS)
  if path_len >= i
  then ok none
  else
    let i1 ← 1#usize <<< path_len
    if leaf_index >= i1
    then ok none
    else
      let current_hash ←
        fastcrypto.merkle.leaf_hash hashHashFunctionT32Inst leaf
      let s := alloc.vec.Vec.deref self.path
      let iter ← core.slice.Slice.iter s
      let current_hash1 ←
        fastcrypto.merkle.MerkleProof.compute_root_loop hashHashFunctionT32Inst
          iter current_hash leaf_index
      ok (some current_hash1)

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<T>}::verify_proof]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 112:4-117:29
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::verify_proof]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleProof<@T>}::verify_proof"]
def fastcrypto.merkle.MerkleProof.verify_proof
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (self : fastcrypto.merkle.MerkleProof T)
  (root : fastcrypto.merkle.Node) (leaf : Slice Std.U8)
  (leaf_index : Std.Usize) :
  Result (core.result.Result Unit fastcrypto.error.FastCryptoError)
  := do
  let o ←
    fastcrypto.merkle.MerkleProof.compute_root hashHashFunctionT32Inst self
      leaf leaf_index
  match o with
  | none =>
    ok (core.result.Result.Err fastcrypto.error.FastCryptoError.InvalidProof)
  | some computed_root =>
    let b ←
      fastcrypto.merkle.Node.Insts.CoreCmpPartialEqNode.eq computed_root root
    if b
    then ok (core.result.Result.Ok ())
    else
      ok (core.result.Result.Err fastcrypto.error.FastCryptoError.InvalidProof)

/-- [fastcrypto::merkle::n_nodes]: loop 0:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 526:4-530:5
    Name pattern: [fastcrypto::merkle::n_nodes] -/
@[rust_loop, rust_fun "fastcrypto::merkle::n_nodes"]
def fastcrypto.merkle.n_nodes_loop
  (lvl_nodes : Std.Usize) (tot_nodes : Std.Usize) :
  Result (Std.Usize × Std.Usize)
  := do
  if lvl_nodes > 1#usize
  then
    let i ← lvl_nodes % 2#usize
    let lvl_nodes1 ← lvl_nodes + i
    let tot_nodes1 ← tot_nodes + lvl_nodes1
    let lvl_nodes2 ← lvl_nodes1 / 2#usize
    fastcrypto.merkle.n_nodes_loop lvl_nodes2 tot_nodes1
  else ok (lvl_nodes, tot_nodes)
partial_fixpoint

/-- [fastcrypto::merkle::n_nodes]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 523:0-523:47
    Name pattern: [fastcrypto::merkle::n_nodes] -/
@[rust_fun "fastcrypto::merkle::n_nodes"]
def fastcrypto.merkle.n_nodes (n_leaves : Std.Usize) : Result Std.Usize := do
  let (lvl_nodes, tot_nodes) ←
    fastcrypto.merkle.n_nodes_loop n_leaves 0#usize
  tot_nodes + lvl_nodes

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::build_from_leaf_hashes]: loop 1:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 404:12-408:13
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes] -/
@[rust_loop, rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes"]
def fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0_loop0
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (nodes : alloc.vec.Vec fastcrypto.merkle.Node)
  (new_level_index : Std.Usize) (index : Std.Usize) :
  Result (alloc.vec.Vec fastcrypto.merkle.Node)
  := do
  if index < new_level_index
  then
    let n ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        fastcrypto.merkle.Node) nodes index
    let i ← index + 1#usize
    let n1 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        fastcrypto.merkle.Node) nodes i
    let parent ← fastcrypto.merkle.inner_hash hashHashFunctionT32Inst n n1
    let nodes1 ← alloc.vec.Vec.push nodes parent
    let index1 ← index + 2#usize
    fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0_loop0
      hashHashFunctionT32Inst nodes1 new_level_index index1
  else ok nodes
partial_fixpoint

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::build_from_leaf_hashes]: loop 0:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 394:8-412:9
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes] -/
@[rust_loop, rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes"]
def fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (nodes : alloc.vec.Vec fastcrypto.merkle.Node)
  (level_nodes : Std.Usize) (prev_level_index : Std.Usize) :
  Result (alloc.vec.Vec fastcrypto.merkle.Node)
  := do
  if level_nodes > 1#usize
  then
    let i ← level_nodes % 2#usize
    let (nodes1, level_nodes1) ←
      if i = 1#usize
      then
        do
        let nodes2 ← alloc.vec.Vec.push nodes fastcrypto.merkle.Node.Empty
        let level_nodes2 ← level_nodes + 1#usize
        ok (nodes2, level_nodes2)
      else ok (nodes, level_nodes)
    let new_level_index ← prev_level_index + level_nodes1
    let nodes2 ←
      fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0_loop0
        hashHashFunctionT32Inst nodes1 new_level_index prev_level_index
    let level_nodes2 ← level_nodes1 / 2#usize
    fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0
      hashHashFunctionT32Inst nodes2 level_nodes2 new_level_index
  else ok nodes
partial_fixpoint

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::build_from_leaf_hashes]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 385:4-385:61
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes] -/
@[rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_leaf_hashes"]
def fastcrypto.merkle.MerkleTree.build_from_leaf_hashes
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (leaf_hashes : alloc.vec.Vec fastcrypto.merkle.Node) :
  Result (fastcrypto.merkle.MerkleTree T)
  := do
  let n_leaves := alloc.vec.Vec.len leaf_hashes
  let i ← fastcrypto.merkle.n_nodes n_leaves
  let i1 ← i - n_leaves
  let leaf_hashes1 ← alloc.vec.Vec.reserve Global leaf_hashes i1
  let nodes ←
    fastcrypto.merkle.MerkleTree.build_from_leaf_hashes_loop0
      hashHashFunctionT32Inst leaf_hashes1 n_leaves 0#usize
  ok { _hash_type := (), nodes, n_leaves }

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::build_from_serialized_slice]: loop 0:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 356:8-359:9
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_serialized_slice]
    Visibility: public -/
@[rust_loop, rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_serialized_slice"]
def fastcrypto.merkle.MerkleTree.build_from_serialized_slice_loop
  {T : Type} {L : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction
  T 32#usize) (coreconvertAsRefLSliceU8Inst : core.convert.AsRef L (Slice
  Std.U8)) (leaves : Slice L)
  (leaf_hashes : alloc.vec.Vec fastcrypto.merkle.Node) (index : Std.Usize) :
  Result (alloc.vec.Vec fastcrypto.merkle.Node)
  := do
  let i := Slice.len leaves
  if index < i
  then
    let t ← Slice.index_usize leaves index
    let s ← coreconvertAsRefLSliceU8Inst.as_ref t
    let n ← fastcrypto.merkle.leaf_hash hashHashFunctionT32Inst s
    let leaf_hashes1 ← alloc.vec.Vec.push leaf_hashes n
    let index1 ← index + 1#usize
    fastcrypto.merkle.MerkleTree.build_from_serialized_slice_loop
      hashHashFunctionT32Inst coreconvertAsRefLSliceU8Inst leaves leaf_hashes1
      index1
  else ok leaf_hashes
partial_fixpoint

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::build_from_serialized_slice]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 350:4-352:23
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_serialized_slice]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::build_from_serialized_slice"]
def fastcrypto.merkle.MerkleTree.build_from_serialized_slice
  {T : Type} {L : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction
  T 32#usize) (coreconvertAsRefLSliceU8Inst : core.convert.AsRef L (Slice
  Std.U8)) (leaves : Slice L) :
  Result (fastcrypto.merkle.MerkleTree T)
  := do
  let i := Slice.len leaves
  let leaf_hashes := alloc.vec.Vec.with_capacity fastcrypto.merkle.Node i
  let leaf_hashes1 ←
    fastcrypto.merkle.MerkleTree.build_from_serialized_slice_loop
      hashHashFunctionT32Inst coreconvertAsRefLSliceU8Inst leaves leaf_hashes
      0#usize
  fastcrypto.merkle.MerkleTree.build_from_leaf_hashes hashHashFunctionT32Inst
    leaf_hashes1

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::root]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 427:4-427:30
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::root]
    Visibility: public -/
@[rust_fun "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::root"]
def fastcrypto.merkle.MerkleTree.root
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (self : fastcrypto.merkle.MerkleTree T) :
  Result fastcrypto.merkle.Node
  := do
  let len := alloc.vec.Vec.len self.nodes
  match len.val with
  | 0 => ok fastcrypto.merkle.Node.Empty
  | _ =>
    let i ← len - 1#usize
    let n ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        fastcrypto.merkle.Node) self.nodes i
    fastcrypto.merkle.Node.Insts.CoreCloneClone.clone n

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::get_proof]: loop 0:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 447:8-460:9
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::get_proof]
    Visibility: public -/
@[rust_loop, rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::get_proof"]
def fastcrypto.merkle.MerkleTree.get_proof_loop
  (v : alloc.vec.Vec fastcrypto.merkle.Node)
  (path : alloc.vec.Vec fastcrypto.merkle.Node) (level_index : Std.Usize)
  (n_level : Std.Usize) (level_base_index : Std.Usize) :
  Result (alloc.vec.Vec fastcrypto.merkle.Node)
  := do
  if n_level > 1#usize
  then
    let i ← n_level % 2#usize
    let n_level1 ← n_level + i
    let b ← core.num.Usize.is_multiple_of level_index 2#usize
    let sibling_index ←
      if b
      then do
           let i1 ← level_base_index + level_index
           i1 + 1#usize
      else do
           let i1 ← level_base_index + level_index
           i1 - 1#usize
    let n ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice
        fastcrypto.merkle.Node) v sibling_index
    let n1 ← fastcrypto.merkle.Node.Insts.CoreCloneClone.clone n
    let path1 ← alloc.vec.Vec.push path n1
    let level_index1 ← level_index / 2#usize
    let level_base_index1 ← level_base_index + n_level1
    let n_level2 ← n_level1 / 2#usize
    fastcrypto.merkle.MerkleTree.get_proof_loop v path1 level_index1 n_level2
      level_base_index1
  else ok path
partial_fixpoint

/-- [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<T>}::get_proof]:
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 436:4-436:82
    Name pattern: [fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::get_proof]
    Visibility: public -/
@[rust_fun
  "fastcrypto::merkle::{fastcrypto::merkle::MerkleTree<@T>}::get_proof"]
def fastcrypto.merkle.MerkleTree.get_proof
  {T : Type} (hashHashFunctionT32Inst : fastcrypto.hash.HashFunction T
  32#usize) (self : fastcrypto.merkle.MerkleTree T) (leaf_index : Std.Usize) :
  Result (core.result.Result (fastcrypto.merkle.MerkleProof T)
    fastcrypto.error.FastCryptoError)
  := do
  if leaf_index >= self.n_leaves
  then
    let a ←
      core.fmt.rt.Argument.new_display Usize.Insts.CoreFmtDisplay leaf_index
    let a1 ←
      core.fmt.Arguments.new
        (Array.make 29#usize [
          26#u8, 76#u8, 101#u8, 97#u8, 102#u8, 32#u8, 105#u8, 110#u8, 100#u8,
          101#u8, 120#u8, 32#u8, 111#u8, 117#u8, 116#u8, 32#u8, 111#u8, 102#u8,
          32#u8, 98#u8, 111#u8, 117#u8, 110#u8, 100#u8, 115#u8, 58#u8, 32#u8,
          192#u8, 0#u8
          ]) (Array.make 1#usize [ a ])
    let s ← alloc.fmt.format a1
    let s1 ← core.hint.must_use s
    ok (core.result.Result.Err (fastcrypto.error.FastCryptoError.GeneralError
      s1))
  else
    let path ←
      fastcrypto.merkle.MerkleTree.get_proof_loop self.nodes (alloc.vec.Vec.new
        fastcrypto.merkle.Node) leaf_index self.n_leaves 0#usize
    ok (core.result.Result.Ok { _hash_type := (), path })

/-- [aeneas_merkle::build_root]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def build_root
  {T : Type} (fastcryptohashHashFunctionT32Inst : fastcrypto.hash.HashFunction
  T 32#usize) (leaves : Slice (alloc.vec.Vec Std.U8)) :
  Result fastcrypto.merkle.Node
  := do
  let mt ←
    fastcrypto.merkle.MerkleTree.build_from_serialized_slice
      fastcryptohashHashFunctionT32Inst
      (alloc.vec.Vec.Insts.CoreConvertAsRefSlice Std.U8 Global) leaves
  fastcrypto.merkle.MerkleTree.root fastcryptohashHashFunctionT32Inst mt

/-- [aeneas_merkle::inclusion_roundtrip]:
    Source: 'src/lib.rs', lines 26:0-37:1
    Visibility: public -/
def inclusion_roundtrip
  {T : Type} (fastcryptohashHashFunctionT32Inst : fastcrypto.hash.HashFunction
  T 32#usize) (leaves : Slice (alloc.vec.Vec Std.U8)) (index : Std.Usize) :
  Result Bool
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (alloc.vec.Vec
      Std.U8)) leaves index
  match o with
  | none => ok false
  | some leaf =>
    let tree ←
      fastcrypto.merkle.MerkleTree.build_from_serialized_slice
        fastcryptohashHashFunctionT32Inst
        (alloc.vec.Vec.Insts.CoreConvertAsRefSlice Std.U8 Global) leaves
    let r ←
      fastcrypto.merkle.MerkleTree.get_proof fastcryptohashHashFunctionT32Inst
        tree index
    match r with
    | core.result.Result.Ok proof =>
      let n ←
        fastcrypto.merkle.MerkleTree.root fastcryptohashHashFunctionT32Inst
          tree
      let s := alloc.vec.Vec.deref leaf
      let r1 ←
        fastcrypto.merkle.MerkleProof.verify_proof
          fastcryptohashHashFunctionT32Inst proof n s index
      core.result.Result.is_ok r1
    | core.result.Result.Err _ => ok false

end FastcryptoMerkle
