-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_merkle]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace FastcryptoMerkle

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [fastcrypto::error::FastCryptoError]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/error.rs', lines 18:0-18:24
    Name pattern: [fastcrypto::error::FastCryptoError]
    Visibility: public -/
@[discriminant isize, rust_type "fastcrypto::error::FastCryptoError"]
inductive fastcrypto.error.FastCryptoError where
| InvalidInput : fastcrypto.error.FastCryptoError
| InputTooShort : Std.Usize → fastcrypto.error.FastCryptoError
| InputTooLong : Std.Usize → fastcrypto.error.FastCryptoError
| InputLengthWrong : Std.Usize → fastcrypto.error.FastCryptoError
| InvalidSignature : fastcrypto.error.FastCryptoError
| InvalidProof : fastcrypto.error.FastCryptoError
| NotEnoughInputs : fastcrypto.error.FastCryptoError
| InvalidMessage : fastcrypto.error.FastCryptoError
| IgnoredMessage : fastcrypto.error.FastCryptoError
| OutOfPresigs : fastcrypto.error.FastCryptoError
| TooManyErrors : Std.Usize → fastcrypto.error.FastCryptoError
| NotEnoughWeight : Std.Usize → fastcrypto.error.FastCryptoError
| GeneralError : String → fastcrypto.error.FastCryptoError
| GeneralOpaqueError : fastcrypto.error.FastCryptoError

/-- [fastcrypto::hash::Digest]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/hash.rs', lines 33:0-33:42
    Name pattern: [fastcrypto::hash::Digest]
    Visibility: public -/
@[rust_type "fastcrypto::hash::Digest"]
structure fastcrypto.hash.Digest (DIGEST_LEN : Std.Usize) where
  digest : Array Std.U8 DIGEST_LEN

/-- Trait declaration: [fastcrypto::hash::HashFunction]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/hash.rs', lines 80:0-80:59
    Name pattern: [fastcrypto::hash::HashFunction]
    Visibility: public -/
@[rust_trait "fastcrypto::hash::HashFunction"
  (parentClauses := ["coredefaultDefaultInst"]) (consts := ["OUTPUT_SIZE"])]
structure fastcrypto.hash.HashFunction (Self : Type) (DIGEST_LENGTH :
  Std.Usize) where
  OUTPUT_SIZE : Result Std.Usize
  coredefaultDefaultInst : core.default.Default Self
  update : forall {Data : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef Data (Slice Std.U8)), Self → Data → Result Self
  finalize : Self → Result (fastcrypto.hash.Digest DIGEST_LENGTH)

/-- [fastcrypto::merkle::Node]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 24:0-24:13
    Name pattern: [fastcrypto::merkle::Node]
    Visibility: public -/
@[discriminant isize, rust_type "fastcrypto::merkle::Node"]
inductive fastcrypto.merkle.Node where
| Empty : fastcrypto.merkle.Node
| Digest : Array Std.U8 32#usize → fastcrypto.merkle.Node

/-- [fastcrypto::merkle::MerkleProof]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 64:0-64:38
    Name pattern: [fastcrypto::merkle::MerkleProof]
    Visibility: public -/
@[rust_type "fastcrypto::merkle::MerkleProof"]
structure fastcrypto.merkle.MerkleProof (T : Type) where
  _hash_type : core.marker.PhantomData T
  path : alloc.vec.Vec fastcrypto.merkle.Node

/-- [fastcrypto::merkle::MerkleTree]
    Source: '/cargo/git/checkouts/fastcrypto-9995504e1c5344d5/d7822bf/fastcrypto/src/merkle.rs', lines 315:0-315:37
    Name pattern: [fastcrypto::merkle::MerkleTree]
    Visibility: public -/
@[rust_type "fastcrypto::merkle::MerkleTree"]
structure fastcrypto.merkle.MerkleTree (T : Type) where
  _hash_type : core.marker.PhantomData T
  nodes : alloc.vec.Vec fastcrypto.merkle.Node
  n_leaves : Std.Usize

end FastcryptoMerkle
