-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_sigma]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import FastcryptoSigma.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open FastcryptoSigma

/-- [fastcrypto::groups::ristretto255::{impl core::ops::arith::Mul<&'_ fastcrypto::groups::ristretto255::RistrettoScalar> for fastcrypto::groups::ristretto255::RistrettoPoint}::mul::<'_>]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/auto_ops-0.3.0/src/binary.rs', lines 63:12-63:59
    Name pattern: [fastcrypto::groups::ristretto255::{core::ops::arith::Mul<fastcrypto::groups::ristretto255::RistrettoPoint, &'_ fastcrypto::groups::ristretto255::RistrettoScalar>}::mul<'_>]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{core::ops::arith::Mul<fastcrypto::groups::ristretto255::RistrettoPoint, &'_ fastcrypto::groups::ristretto255::RistrettoScalar>}::mul<'_>"]
axiom
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
  :
  fastcrypto.groups.ristretto255.RistrettoPoint →
    fastcrypto.groups.ristretto255.RistrettoScalar → Result
    fastcrypto.groups.ristretto255.RistrettoPoint

/-- [fastcrypto::groups::ristretto255::{impl core::ops::arith::Mul<&'_ fastcrypto::groups::ristretto255::RistrettoScalar> for fastcrypto::groups::ristretto255::RistrettoScalar}::mul::<'_>]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/auto_ops-0.3.0/src/binary.rs', lines 63:12-63:59
    Name pattern: [fastcrypto::groups::ristretto255::{core::ops::arith::Mul<fastcrypto::groups::ristretto255::RistrettoScalar, &'_ fastcrypto::groups::ristretto255::RistrettoScalar>}::mul<'_>]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{core::ops::arith::Mul<fastcrypto::groups::ristretto255::RistrettoScalar, &'_ fastcrypto::groups::ristretto255::RistrettoScalar>}::mul<'_>"]
axiom
  fastcrypto.groups.ristretto255.RistrettoScalar.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
  :
  fastcrypto.groups.ristretto255.RistrettoScalar →
    fastcrypto.groups.ristretto255.RistrettoScalar → Result
    fastcrypto.groups.ristretto255.RistrettoScalar
/-- [fastcrypto::groups::ristretto255::{impl core::cmp::PartialEq<fastcrypto::groups::ristretto255::RistrettoPoint> for fastcrypto::groups::ristretto255::RistrettoPoint}::eq]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 37:38-37:47
    Name pattern: [fastcrypto::groups::ristretto255::{core::cmp::PartialEq<fastcrypto::groups::ristretto255::RistrettoPoint, fastcrypto::groups::ristretto255::RistrettoPoint>}::eq]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{core::cmp::PartialEq<fastcrypto::groups::ristretto255::RistrettoPoint, fastcrypto::groups::ristretto255::RistrettoPoint>}::eq"]
axiom
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreCmpPartialEqRistrettoPoint.eq
  :
  fastcrypto.groups.ristretto255.RistrettoPoint →
    fastcrypto.groups.ristretto255.RistrettoPoint → Result Bool

/-- [fastcrypto::groups::ristretto255::{impl core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoPoint> for fastcrypto::groups::ristretto255::RistrettoPoint}::add]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 37:53-37:56
    Name pattern: [fastcrypto::groups::ristretto255::{core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoPoint, fastcrypto::groups::ristretto255::RistrettoPoint>}::add]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoPoint, fastcrypto::groups::ristretto255::RistrettoPoint>}::add"]
axiom
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithAddRistrettoPoint.add
  :
  fastcrypto.groups.ristretto255.RistrettoPoint →
    fastcrypto.groups.ristretto255.RistrettoPoint → Result
    fastcrypto.groups.ristretto255.RistrettoPoint

/-- [fastcrypto::groups::ristretto255::{impl fastcrypto::groups::GroupElement for fastcrypto::groups::ristretto255::RistrettoPoint}::generator]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 112:4-112:26
    Name pattern: [fastcrypto::groups::ristretto255::{fastcrypto::groups::GroupElement<fastcrypto::groups::ristretto255::RistrettoPoint>}::generator]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{fastcrypto::groups::GroupElement<fastcrypto::groups::ristretto255::RistrettoPoint>}::generator"]
axiom
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.FastcryptoGroupsGroupElement.generator
  : Result fastcrypto.groups.ristretto255.RistrettoPoint

/-- [fastcrypto::groups::ristretto255::{impl core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoScalar> for fastcrypto::groups::ristretto255::RistrettoScalar}::add]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 153:50-153:53
    Name pattern: [fastcrypto::groups::ristretto255::{core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoScalar, fastcrypto::groups::ristretto255::RistrettoScalar>}::add]
    Visibility: public -/
@[rust_fun
  "fastcrypto::groups::ristretto255::{core::ops::arith::Add<fastcrypto::groups::ristretto255::RistrettoScalar, fastcrypto::groups::ristretto255::RistrettoScalar>}::add"]
axiom
  fastcrypto.groups.ristretto255.RistrettoScalar.Insts.CoreOpsArithAddRistrettoScalar.add
  :
  fastcrypto.groups.ristretto255.RistrettoScalar →
    fastcrypto.groups.ristretto255.RistrettoScalar → Result
    fastcrypto.groups.ristretto255.RistrettoScalar
