-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_sigma]: function definitions
import Aeneas
import FastcryptoSigma.Code.Types
import FastcryptoSigma.Code.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace FastcryptoSigma

/-- [fastcrypto_tbls::nizk::dl_sigma::commit::<fastcrypto::groups::ristretto255::RistrettoPoint>]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto-tbls/src/nizk.rs', lines 113:4-113:62
    Name pattern: [fastcrypto_tbls::nizk::dl_sigma::commit<fastcrypto::groups::ristretto255::RistrettoPoint>]
    Visibility: public -/
@[rust_fun
  "fastcrypto_tbls::nizk::dl_sigma::commit<fastcrypto::groups::ristretto255::RistrettoPoint>"]
def fastcrypto_tbls.nizk.dl_sigma.commitRistrettoPoint
  (nonce : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result fastcrypto.groups.ristretto255.RistrettoPoint
  := do
  let rp ←
    fastcrypto.groups.ristretto255.RistrettoPoint.Insts.FastcryptoGroupsGroupElement.generator
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
    rp nonce

/-- [fastcrypto_tbls::nizk::dl_sigma::respond::<fastcrypto::groups::ristretto255::RistrettoPoint>]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto-tbls/src/nizk.rs', lines 118:4-122:22
    Name pattern: [fastcrypto_tbls::nizk::dl_sigma::respond<fastcrypto::groups::ristretto255::RistrettoPoint>]
    Visibility: public -/
@[rust_fun
  "fastcrypto_tbls::nizk::dl_sigma::respond<fastcrypto::groups::ristretto255::RistrettoPoint>"]
def fastcrypto_tbls.nizk.dl_sigma.respondRistrettoPoint
  (witness : fastcrypto.groups.ristretto255.RistrettoScalar)
  (nonce : fastcrypto.groups.ristretto255.RistrettoScalar)
  (challenge : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result fastcrypto.groups.ristretto255.RistrettoScalar
  := do
  let rs ←
    fastcrypto.groups.ristretto255.RistrettoScalar.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
      challenge witness
  fastcrypto.groups.ristretto255.RistrettoScalar.Insts.CoreOpsArithAddRistrettoScalar.add
    rs nonce

/-- [fastcrypto_tbls::nizk::is_valid_relation::<fastcrypto::groups::ristretto255::RistrettoPoint>]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto-tbls/src/nizk.rs', lines 207:0-213:9
    Name pattern: [fastcrypto_tbls::nizk::is_valid_relation<fastcrypto::groups::ristretto255::RistrettoPoint>] -/
@[rust_fun
  "fastcrypto_tbls::nizk::is_valid_relation<fastcrypto::groups::ristretto255::RistrettoPoint>"]
def fastcrypto_tbls.nizk.is_valid_relationRistrettoPoint
  (e1 : fastcrypto.groups.ristretto255.RistrettoPoint)
  (e2 : fastcrypto.groups.ristretto255.RistrettoPoint)
  (e3 : fastcrypto.groups.ristretto255.RistrettoPoint)
  (z : fastcrypto.groups.ristretto255.RistrettoScalar)
  (c : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result Bool
  := do
  let rp ←
    fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
      e2 c
  let left ←
    fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithAddRistrettoPoint.add
      e1 rp
  let right ←
    fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreOpsArithMulSharedRistrettoScalar.mul
      e3 z
  fastcrypto.groups.ristretto255.RistrettoPoint.Insts.CoreCmpPartialEqRistrettoPoint.eq
    left right

/-- [fastcrypto_tbls::nizk::dl_sigma::verify::<fastcrypto::groups::ristretto255::RistrettoPoint>]:
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto-tbls/src/nizk.rs', lines 127:4-132:13
    Name pattern: [fastcrypto_tbls::nizk::dl_sigma::verify<fastcrypto::groups::ristretto255::RistrettoPoint>]
    Visibility: public -/
@[rust_fun
  "fastcrypto_tbls::nizk::dl_sigma::verify<fastcrypto::groups::ristretto255::RistrettoPoint>"]
def fastcrypto_tbls.nizk.dl_sigma.verifyRistrettoPoint
  (public_key : fastcrypto.groups.ristretto255.RistrettoPoint)
  (commitment : fastcrypto.groups.ristretto255.RistrettoPoint)
  (challenge : fastcrypto.groups.ristretto255.RistrettoScalar)
  (response : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result Bool
  := do
  let rp ←
    fastcrypto.groups.ristretto255.RistrettoPoint.Insts.FastcryptoGroupsGroupElement.generator
  fastcrypto_tbls.nizk.is_valid_relationRistrettoPoint commitment public_key rp
    response challenge

/-- [aeneas_sigma::commit]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def commit
  (nonce : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result fastcrypto.groups.ristretto255.RistrettoPoint
  := do
  fastcrypto_tbls.nizk.dl_sigma.commitRistrettoPoint nonce

/-- [aeneas_sigma::respond]:
    Source: 'src/lib.rs', lines 16:0-22:1
    Visibility: public -/
def respond
  (witness : fastcrypto.groups.ristretto255.RistrettoScalar)
  (nonce : fastcrypto.groups.ristretto255.RistrettoScalar)
  (challenge : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result fastcrypto.groups.ristretto255.RistrettoScalar
  := do
  fastcrypto_tbls.nizk.dl_sigma.respondRistrettoPoint witness nonce challenge

/-- [aeneas_sigma::verify]:
    Source: 'src/lib.rs', lines 25:0-32:1
    Visibility: public -/
def verify
  (public_key : fastcrypto.groups.ristretto255.RistrettoPoint)
  (commitment : fastcrypto.groups.ristretto255.RistrettoPoint)
  (challenge : fastcrypto.groups.ristretto255.RistrettoScalar)
  (response : fastcrypto.groups.ristretto255.RistrettoScalar) :
  Result Bool
  := do
  fastcrypto_tbls.nizk.dl_sigma.verifyRistrettoPoint public_key commitment
    challenge response

end FastcryptoSigma
