-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_sigma]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [fastcrypto::groups::ristretto255::RistrettoScalar]
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 156:0-156:26
    Name pattern: [fastcrypto::groups::ristretto255::RistrettoScalar]
    Visibility: public -/
@[rust_type "fastcrypto::groups::ristretto255::RistrettoScalar"]
axiom fastcrypto.groups.ristretto255.RistrettoScalar : Type

/-- [fastcrypto::groups::ristretto255::RistrettoPoint]
    Source: '/Users/saikrishnadeepakmaram/Desktop/fastcrypto/fastcrypto/src/groups/ristretto255.rs', lines 38:0-38:25
    Name pattern: [fastcrypto::groups::ristretto255::RistrettoPoint]
    Visibility: public -/
@[rust_type "fastcrypto::groups::ristretto255::RistrettoPoint"]
axiom fastcrypto.groups.ristretto255.RistrettoPoint : Type
