-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aeneas_sigma]: type definitions
import Aeneas
import FastcryptoSigma.Code.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace FastcryptoSigma

end FastcryptoSigma
